### ISSUE TITLE
Source code displayed in 2 frames

### ISSUE THREAD

**Issue by RemiBou** [barryclark/jekyll-now#1223] opened 2018-06-28 07:38 UTC
Hi 

here is my blog post https://remibou.github.io/Using-Mediatr-on-AspNetCore2.1-Week-25/, if you scroll down, you can see that the source code is displayed inside 2 frames.

Here is this article markdown file https://github.com/RemiBou/remibou.github.io/blob/master/_posts/2018-6-22-Using-Mediatr-on-AspNetCore2.1-Week-25.md (it's displayed well inside github)

I use this "```cs" around my code, I don't know what is wrong here or if it's a bug with C#

**Comment by ldjb** [comment] 2018-06-28 13:02
Hi, @RemiBou!

This is a known issue with Jekyll Now. To fix this, you should update your `_sass/_highlights.scss` file.

You will need to change the `.highlight` selector at the top of the file to `pre.highlight`.
Whilst you're at it, you should probably change `overflow: scroll;` to `overflow: auto;` to prevent scrollbars from appearing unnecessarily.

You can see a diff of these changes here at ldjb/jekyll-now@76ed8f3.

I hope this helps. :smile:

**Comment by RemiBou** [comment] 2018-06-28 13:54
Ok I changed the theme anyway thanks

**Comment by 64kramsystem** [comment] 2018-07-02 08:54
Duplicate of #1055.

**Closed as completed** 2018-07-13 08:26 UTC
